---
- hosts: CentOS_serv
  become: true
  tasks:

  - name: install apache, PHP support and Update repository
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package}}"
      state: latest
      update_cache: yes


